services:
  - type: web
    name: hangman-multiplayer
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app --worker-class eventlet -b 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PORT
        value: 10000